apiVersion: v1
kind: Pod
metadata:
  name: flask
  namespace: flask
  labels:
    app: flask
spec:
  containers:
    - name: flask-app
      image: swastik2929/sampleflask:new
      ports:
        - containerPort: 8000
